common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *common
  database: okonote_development

test:
  <<: *common
  database: okonote_test

staging:
  <<: *common
  database: okonote_staging

production:
  <<: *common
  database: okonote_production